### ISSUE TITLE
Docs: Feedback for Configuring Management Center

### ISSUE THREAD

**Issue by mtyazici** [hazelcast/management-center-docs#152]
Hi, I have some feedback about [this page](https://github.com/hazelcast/management-center-docs/edit/main/docs/modules/deploy-manage/pages/configuring.adoc)

In  [Where Management Center Saves Data](https://docs.hazelcast.com/management-center/latest/deploy-manage/configuring#where-management-center-saves-data), there is a typo as `hazlecast-mc`.

**Comment by Serdaro** [comment]
Thanks @mtyazici !
