### ISSUE TITLE
Docs: Feedback for Viewing a Cluster License

### ISSUE THREAD

**Issue by anatoly-hazelcast** [hazelcast/management-center-docs#172]
Hi, I have some feedback about [this page](https://docs.hazelcast.com/management-center/5.2-SNAPSHOT/clusters/cluster-license#hide-nav) (5.1 as well)
1. I've noticed we don't really have the "Current Cluster Size" in the "Licensed Cluster Members" section:
![image](https://user-images.githubusercontent.com/95342781/164219245-eb8ea174-3c4e-4046-a031-588e2cf61b99.png)
We can always see the member count on a left bar though
2. All 4 links on a bottom of the page are the same and leading to https://docs.hazelcast.com/hazelcast/5.2-snapshot/deploy/enterprise-licenses without anchors

**Comment by JakeSCahill** [comment]
Is 1. still correct as of 5.2-snapshot? Did we remove that information?

**Comment by anatoly-hazelcast** [comment]
@JakeSCahill , apologies, turned out I mixed up the Cluster License and Management Center License pages.
So, item 1. is irrelevant for both version.
