### ISSUE TITLE
Docs: Feedback for System Properties and Environment Variables

### ISSUE THREAD

**Issue by utkukaratas** [hazelcast/management-center-docs#234]
Hi, I have some feedback about [this page](https://github.com/hazelcast/management-center-docs/edit/main/docs/modules/deploy-manage/pages/system-properties.adoc)

"MC_AUDIT_LOG_ENABLED" should be "MC_AUDITLOG_ENABLED" (also for 5.2 and maybe older versions too)

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/management-center-docs/pull/235
