### ISSUE TITLE
Docs: Feedback for Installing and Starting Management Center

### ISSUE THREAD

**Issue by jgardiner68** [hazelcast/management-center-docs#249]
Hi, I have some feedback about [this page](https://github.com/hazelcast/management-center-docs/edit/main/docs/modules/getting-started/pages/install.adoc)

RU link (last link) is a link to itself

**Comment by Serdaro** [comment]
Was fixed for the snapshot version. Also [fixed](https://github.com/hazelcast/management-center-docs/commit/8b19989774594e631bb2257b2274c925247c4452) in 5.3.
