### ISSUE TITLE
Docs: Feedback for System Properties and Environment Variables

### ISSUE THREAD

**Issue by utkukaratas** [hazelcast/management-center-docs#272]
Hi, I have some feedback about [this page](https://github.com/hazelcast/management-center-docs/edit/main/docs/modules/deploy-manage/pages/system-properties.adoc)

default value of **MC_ALLOW_MULTIPLE_LOGIN** is **TRUE** but in the document it says it is **FALSE**

cc @anatoly-hazelcast @promanenko @zhmaeff

**Comment by promanenko** [comment]
@utkukaratas please create a PR to update docs to `true` as a default value

**Comment by utkukaratas** [comment]
fixed by #278
