### ISSUE TITLE
Docs: Feedback for Monitoring Clients

### ISSUE THREAD

**Issue by utkukaratas** [hazelcast/management-center-docs#30]
Hi, I have some feedback about [this page](https://github.com/hazelcast/management-center-docs/blob/v4.2021.03/docs/modules/monitor-imdg/pages/monitor-clients.adoc)

paragraph starting with "Let’s create a new filter list" is unformatted.

**Comment by Serdaro** [comment]
It was fixed in 4.2021.04-SNAPSHOT version, let me also fix on the current stable one. Thanks a lot @utkukaratas

**Comment by Serdaro** [comment]
Fixed: https://docs.hazelcast.com/management-center/4.2021.03/monitor-imdg/monitor-clients.html#changing-cluster-client-filtering-example
