### ISSUE TITLE
Docs: Feedback for System Properties and Environment Variables

### ISSUE THREAD

**Issue by 7erry** [hazelcast/management-center-docs#367]
Hi, I have some feedback about [this page](https://github.com/hazelcast/management-center-docs/edit/main/docs/modules/deploy-manage/pages/system-properties.adoc)

we forgot the -D for java hazelcast.mc.http.port=80

**Comment by amandalindsay** [comment]
Fixed in PR: https://github.com/hazelcast/management-center-docs/pull/417
