### ISSUE TITLE
Docs: Feedback for Monitoring Clients

### ISSUE THREAD

**Issue by jgardiner68** [hazelcast/management-center-docs#67]
Hi, I have some feedback about [this page](https://github.com/hazelcast/management-center-docs/edit/v/4.2021.06/docs/modules/monitor-imdg/pages/monitor-clients.adoc)

Can we please make MC Client Filtering its own section for MC5 documentation beneath "Monitoring Clients" ?  It's an important feature that needs more prominence.

**Comment by Serdaro** [comment]
Fixed with https://github.com/hazelcast/management-center-docs/pull/69
